
#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define BOARD_WIDTH 8
#define BOARD_HEIGHT 8
#define NUMBER_OF_BOARD_CELLS (BOARD_WIDTH * BOARD_HEIGHT)

#define MAX_NUMBER_OF_INGAME_PIECES 24

#define MAX_NUMBER_OF_INGAME_MONSTERS 8
#define NUMBER_OF_PLAYERS 1
#define NUMBER_OF_INGAME_ENTITIES (NUMBER_OF_PLAYERS + MAX_NUMBER_OF_INGAME_MONSTERS)

#define MONSTER_START_INDEX 1

#define MAX_NUMBER_OF_PUZZLE_SPACES 6

#endif