#!/bin/bash


echo "#ifndef AUTOGENERATED_BGM_IDS_HEADER"
echo "#define AUTOGENERATED_BGM_IDS_HEADER"

echo ""
echo ""

count=0
for i in source/*.mid; do
  nm=${i#source/}
  name=${nm%.mid}

  echo "/* $nm  */"

  sfxdefine="#define TRACK_$count_${name^^} $count"
  echo ${sfxdefine}
  echo ""

  count=$((count+1))
done

echo "#define TRACK_COUNT $count"
echo ""


echo ""
echo "#endif"
