#ifndef AUTOGENERATED_BGM_IDS_HEADER
#define AUTOGENERATED_BGM_IDS_HEADER


/* 01_puzzle_time.mid  */
#define TRACK_01_PUZZLE_TIME 0

/* 02_drums_test.mid  */
#define TRACK_02_DRUMS_TEST 1

/* 03_pitched_drums.mid  */
#define TRACK_03_PITCHED_DRUMS 2

/* 04_wood_block.mid  */
#define TRACK_04_WOOD_BLOCK 3

/* 05_overture.mid  */
#define TRACK_05_OVERTURE 4

/* 06_doomed_heroes.mid  */
#define TRACK_06_DOOMED_HEROES 5

/* 07_contemplation.mid  */
#define TRACK_07_CONTEMPLATION 6

/* 08_overture_ending.mid  */
#define TRACK_08_OVERTURE_ENDING 7

/* 09_between_the_floors.mid  */
#define TRACK_09_BETWEEN_THE_FLOORS 8

/* 10_harbour.mid  */
#define TRACK_10_HARBOUR 9

/* 11_arena1.mid  */
#define TRACK_11_ARENA1 10

#define TRACK_COUNT 11


#endif
