#ifndef AUTOGENERATED_BGM_IDS_HEADER
#define AUTOGENERATED_BGM_IDS_HEADER


/* 01_test_track_a.mid  */
#define TRACK_01_TEST_TRACK_A 0

/* 02_drums_test.mid  */
#define TRACK_02_DRUMS_TEST 1

/* 03_pitched_drums.mid  */
#define TRACK_03_PITCHED_DRUMS 2

/* 04_wood_block.mid  */
#define TRACK_04_WOOD_BLOCK 3

/* 05_overture.mid  */
#define TRACK_05_OVERTURE 4

/* 06_doomed_heroes.mid  */
#define TRACK_06_DOOMED_HEROES 5

#define TRACK_COUNT 6


#endif
