#ifndef AUTOGENERATED_SFX_IDS_HEADER
#define AUTOGENERATED_SFX_IDS_HEADER


/* 01_laser1.aifc  */
#define SFX_01_LASER1 0

/* 02_nobody_bip.aifc  */
#define SFX_02_NOBODY_BIP 1

/* 03_protag_bip.aifc  */
#define SFX_03_PROTAG_BIP 2

/* 04_zoom_in.aifc  */
#define SFX_04_ZOOM_IN 3

/* 05_illegal_move.aifc  */
#define SFX_05_ILLEGAL_MOVE 4

/* 06_move_cursor.aifc  */
#define SFX_06_MOVE_CURSOR 5

/* 06_tense_move_cursor.aifc  */
#define SFX_06_TENSE_MOVE_CURSOR 6

/* 07_onto_puzzle_space.aifc  */
#define SFX_07_ONTO_PUZZLE_SPACE 7

/* 08_confirm_move.aifc  */
#define SFX_08_CONFIRM_MOVE 8

/* 09_floor_clear.aifc  */
#define SFX_09_FLOOR_CLEAR 9

/* 10_player_die.aifc  */
#define SFX_10_PLAYER_DIE 10

/* 11_menu_confirm.aifc  */
#define SFX_11_MENU_CONFIRM 11

/* 12_menu_back.aifc  */
#define SFX_12_MENU_BACK 12

/* 13_zatt_bip.aifc  */
#define SFX_13_ZATT_BIP 13

/* 14_zatt_screaming_bip.aifc  */
#define SFX_14_ZATT_SCREAMING_BIP 14

/* 15_monster_bip.aifc  */
#define SFX_15_MONSTER_BIP 15

/* 16_elder_bip.aifc  */
#define SFX_16_ELDER_BIP 16

/* 17_ogre_grunt.aifc  */
#define SFX_17_OGRE_GRUNT 17

/* 18_ogre_bip.aifc  */
#define SFX_18_OGRE_BIP 18

/* 19_ogre_hurt.aifc  */
#define SFX_19_OGRE_HURT 19

/* 20_player_hurt_0.aifc  */
#define SFX_20_PLAYER_HURT_0 20

/* 21_player_hurt_1.aifc  */
#define SFX_21_PLAYER_HURT_1 21

/* 22_player_hurt_2.aifc  */
#define SFX_22_PLAYER_HURT_2 22

/* 23_vo_line_0.aifc  */
#define SFX_23_VO_LINE_0 23

/* 24_vo_line_1.aifc  */
#define SFX_24_VO_LINE_1 24

/* 25_vo_line_2.aifc  */
#define SFX_25_VO_LINE_2 25

/* 26_vo_line_3.aifc  */
#define SFX_26_VO_LINE_3 26

/* 27_vo_line_4.aifc  */
#define SFX_27_VO_LINE_4 27

/* 28_vo_line_5.aifc  */
#define SFX_28_VO_LINE_5 28

/* 29_vo_line_6.aifc  */
#define SFX_29_VO_LINE_6 29

/* 30_vo_line_7.aifc  */
#define SFX_30_VO_LINE_7 30

/* 31_n64_noises.aifc  */
#define SFX_31_N64_NOISES 31

/* 32_b_bip.aifc  */
#define SFX_32_B_BIP 32

/* 33_call.aifc  */
#define SFX_33_CALL 33

/* 34_mouse_bip.aifc  */
#define SFX_34_MOUSE_BIP 34

/* 35_queen_bip.aifc  */
#define SFX_35_QUEEN_BIP 35

#define SFX_COUNT 36


#endif
